package com.example.BetrayalAtBaldursGate.tiles;

public enum Door {

    CURSED_STATUE,
    TRASH_PILE,
    SHRINE_TO_GARGAUTH,
    BELOVED_RANGER_STATUE,
    WEAPON_SHOP,
    HALL_OF_WONDERS,
    MURDER_ROW,
    SMITHY,
    STOREHOUSE,
    MARKETPLACE,
    HOUSE_OF_BLOOD,
    MANSION,
    FOUNTAIN,
    KITCHEN,
    INNER_CHAMBER,
    ELFSONG_TAVERN,
    GRAY_HARBOUR,
    TRADING_POST,
    EXECUTIONERS_BLOCK,
    FELOGYRS_FIREWORKS,
    SPYS_ROOST,
    HAUNTED_ALLEY,
    DEAD_END,
    SORCEROUS_SUNDRIES,
    TEMPLE_OF_UMBERLEE,
    ROSE_PORTAL,
    WATERFRONT,
    FALSE
}
